// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqfxvwnupslywtaxywcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxZnh2d251cHNseXd0YXh5d2N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzMyODYsImV4cCI6MjA3MDgwOTI4Nn0.Qn2cWYMYdCZiMf7ppGhXt15YSWLNIJ7XKzQRAOhRBVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});